### ISSUE TITLE
Memmory leak

### ISSUE THREAD

**Issue by michalpaukert** [levchak0910/vue3-ssr-realworld-example-app#1]
When I try to benchmark this solution, it consumes more and more memmory with every request.
So when I tried to benchmark with apache benchmark `ab -c 10 -n 1000 http://localhost:8080/`  
![image](https://user-images.githubusercontent.com/36043389/121717501-89021700-cae1-11eb-97ba-180ea97b7673.png)
Memmory consumption is more than 1GB of memmory.
Could you help me with investigation what is wrong with this?

How to reproduce:
1. Clone this repository
2. run npm install
3. run npm run serve
4. benchmark with apache benchmark `ab -c 10 -n 1000 http://localhost:8080/`

**Comment by levchak0910** [comment]
Hi
Thanks for report 
Sorry, currently I don't have time to investigate this problem

Problem could possibly be with global component registration or with global store

If you find a solution, please share your experience

**Comment by levchak0910** [comment]
Hi @michalpaukert 
After some time :smile: I returned to work with SSR and encountered same problem on another project
The problem lies somewhere in vue itself. I have reported [issue](https://github.com/vuejs/vue-next/issues/5208) there

**Comment by levchak0910** [comment]
Memory leak issue was closed in vue@3.2.27
